version: '3'

services:
  mysql:
    image: mysql:5.6.27
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql